# -*- encoding: utf-8 -*-
# stub: racc 1.5.2 ruby lib
# stub: ext/racc/cparse/extconf.rb

Gem::Specification.new do |s|
  s.name = "racc".freeze
  s.version = "1.5.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Minero Aoki".freeze, "Aaron Patterson".freeze]
  s.date = "2023-03-30"
  s.description = "Racc is a LALR(1) parser generator.\n  It is written in Ruby itself, and generates Ruby program.\n\n  NOTE: Ruby 1.8.x comes with Racc runtime module.  You\n  can run your parsers generated by racc 1.4.x out of the\n  box.\n".freeze
  s.email = [nil, "aaron@tenderlovemaking.com".freeze]
  s.executables = ["racc".freeze]
  s.extensions = ["ext/racc/cparse/extconf.rb".freeze]
  s.extra_rdoc_files = ["README.ja.rdoc".freeze, "README.rdoc".freeze, "rdoc/en/NEWS.en.rdoc".freeze, "rdoc/en/grammar.en.rdoc".freeze, "rdoc/ja/NEWS.ja.rdoc".freeze, "rdoc/ja/debug.ja.rdoc".freeze, "rdoc/ja/grammar.ja.rdoc".freeze, "rdoc/ja/parser.ja.rdoc".freeze, "README.ja.rdoc".freeze, "README.rdoc".freeze]
  s.files = ["README.ja.rdoc".freeze, "README.rdoc".freeze, "anyolite/build/src_mri/lib/racc.rb".freeze, "anyolite/build/src_mri/lib/racc/compat.rb".freeze, "anyolite/build/src_mri/lib/racc/debugflags.rb".freeze, "anyolite/build/src_mri/lib/racc/exception.rb".freeze, "anyolite/build/src_mri/lib/racc/grammar.rb".freeze, "anyolite/build/src_mri/lib/racc/grammarfileparser.rb".freeze, "anyolite/build/src_mri/lib/racc/info.rb".freeze, "anyolite/build/src_mri/lib/racc/iset.rb".freeze, "anyolite/build/src_mri/lib/racc/logfilegenerator.rb".freeze, "anyolite/build/src_mri/lib/racc/parser-text.rb".freeze, "anyolite/build/src_mri/lib/racc/parser.rb".freeze, "anyolite/build/src_mri/lib/racc/parserfilegenerator.rb".freeze, "anyolite/build/src_mri/lib/racc/sourcetext.rb".freeze, "anyolite/build/src_mri/lib/racc/state.rb".freeze, "anyolite/build/src_mri/lib/racc/statetransitiontable.rb".freeze, "anyolite/build/src_mri/lib/racc/static.rb".freeze, "bin/racc".freeze, "ext/racc/cparse/extconf.rb".freeze, "rdoc/en/NEWS.en.rdoc".freeze, "rdoc/en/grammar.en.rdoc".freeze, "rdoc/ja/NEWS.ja.rdoc".freeze, "rdoc/ja/debug.ja.rdoc".freeze, "rdoc/ja/grammar.ja.rdoc".freeze, "rdoc/ja/parser.ja.rdoc".freeze]
  s.homepage = "http://i.loveruby.net/en/projects/racc/".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.rdoc_options = ["--main".freeze, "README.rdoc".freeze]
  s.rubygems_version = "3.2.33".freeze
  s.summary = "Racc is a LALR(1) parser generator".freeze
end
